name: didi
description: App de mensagens.
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  dashed_container: ^1.0.1
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+3
  get: ^2.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
        - assets/images/
        - assets/images/status/
